# Generated by Django 4.1.1 on 2022-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Do not fill in here', unique=True, verbose_name='Slug'),
        ),
    ]
